import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import '../libs/dbConnect'
import { useQuery } from '@apollo/client'
import { GETUSERS } from '../graphql/schema'


export default function Home() {

  const {data, loading, error} = useQuery(GETUSERS)

  console.log(data, loading, error);
  if(error){
    return <h2>Ha ocurrido un error{error}</h2>
  }
  if(loading){
    return <h3>Cargando---</h3>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Hola</h2>
        {/* {data?.users?.map(el=>(
         <>
         <h2>{el.name}</h2>
          <h2>{el.email}</h2>
          <h2>{el.ciudad}</h2>
         </> 
        ))} */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
